# Site settings
title: 八九六四纪念 支持台湾独立网站
SEOTitle: 天安门 八九六四纪念 支持台湾独立网站
description: "天安门 八九六四纪念 支持台湾独立网站"
keyword: "天安门 八九六四纪念 支持台湾独立网站，北京 中国"
url: "https://recordchina.github.io"
baseurl: ""

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Build settings
permalink: pretty
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
# 这里的 "qsewr" 应该是你特定的文件夹名称，如果不存在该文件夹，建议删除此行
include: ["qsewr"]

# Plugins
plugins:
  - jekyll-sitemap
